# Generated by Django 4.2.28 on 2026-02-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mlmodel', '0001_initial'),
        ('camera', '0003_alter_camera_rtsp_url'),
        ('pipeline', '0002_pipeline_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera')),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlmodel.mlmodel')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='pipeline.pipeline')),
            ],
        ),
    ]
