# Generated by Django 4.2.28 on 2026-02-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='frame_image',
            field=models.ImageField(blank=True, null=True, upload_to='violations/%Y/%m/%d/'),
        ),
    ]
