# Generated by Django 4.2.28 on 2026-02-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0002_violation_frame_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='detections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
