# Generated by Django 4.2.28 on 2026-03-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0003_violation_detections'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='plate_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
