# Generated by Django 4.2.28 on 2026-03-03 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='model_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='ml_models/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='threshold_parameter',
            field=models.FloatField(default=0.5),
        ),
    ]
