# Generated by Django 4.2.28 on 2026-03-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0002_mlmodel_model_file_alter_mlmodel_threshold_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='model_file',
        ),
    ]
