# Generated by Django 4.2.28 on 2026-02-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0003_alter_camera_rtsp_url'),
        ('mlmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='camera.camera')),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='mlmodel.mlmodel')),
            ],
        ),
    ]
