# Generated by Django 4.2.28 on 2026-03-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_pipeline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='queue_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('starting', 'Starting'), ('active', 'Active'), ('stopping', 'Stopping'), ('error', 'Error')], default='inactive', max_length=20),
        ),
    ]
