# Generated by Django 4.2.28 on 2026-03-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_pipeline_queue_name_alter_pipeline_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='status',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
