# Generated by Django 4.2.28 on 2026-03-05 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_remove_pipeline_status_pipeline_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='use_case',
            field=models.CharField(default=datetime.datetime(2026, 3, 5, 16, 18, 49, 486103, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
