# Generated by Django 4.2.28 on 2026-03-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_pipeline_use_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='use_case',
            field=models.CharField(default='helmet', max_length=100),
        ),
    ]
