# Generated by Django 4.2.28 on 2026-03-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_alter_pipeline_use_case'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(fields=('camera', 'ml_model'), name='unique_camera_mlmodel_pipeline'),
        ),
    ]
