# Generated by Django 4.2.28 on 2026-02-19 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes=['rtsp', 'http', 'https'])]),
        ),
    ]
